version: '3.4'
#
#networks:
#  dockerapi-dev:
#    driver: bridge

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: weatherforecast
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
#    ports:
#      - 3600:3600
    volumes:
      - dbdata:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
    restart: always
  weatherforecastapp:
    depends_on:
      - db
    image: mrkayun/weatherforecast:runtime
    environment:
      connection: "server=localhost;userid=dbuser;password=dbuserpassword;database=weatherforecast;"
    build:
      context: .
    ports:
      - "8080:5000"
#  postgres_image:
#    container_name: npgdbweather
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    restart: always
#    volumes:
#      - ./dbscripts/data.sql:/docker-entrypoint-initdb.d/data.sql
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: weatherdb
#    networks:
#      - dockerapi-dev
volumes:
  dbdata: